const langs = {
	'en-US': {
	  'st201': 'Created',
	  'st400': 'Bad Request',
	  'st401': 'You must login',
	  'st403': 'You have not permissions',
	  'st404': 'Not found',
	  'missing': 'Missing fields:',
	  'invalidpasswd': 'Invalid code or password',
	  'alreadyexists': 'Already Exists',
	  'code': 'Code',
	  'passwd': 'Password',
	  'name': 'Name',
	  'type': 'Type',
	  'content': 'Content',
	},
	'es-ES': {
	  'st201': 'Creado',
	  'st400': 'Petición no válida',
	  'st401': 'Debes identificarte',
	  'st403': 'No tienes permisos',
	  'st404': 'No encontrado',
	  'missing': 'Faltan campos:',
	  'invalidpasswd': 'Código o contraseña no válidos',
	  'alreadyexists': 'Ya existe',
	  'code': 'Código',
	  'passwd': 'Contraseña',
	  'name': 'Nombre',
	  'type': 'Tipo',
	  'content': 'Contenido',
	},
	'fr-FR': {
	  'st201': 'Créé',
	  'st400': 'Mauvaise demande',
	  'st401': 'Vous devez vous connecter',
	  'st403': 'Vous n\'avez pas de droits d\'accès',
	  'st404': 'Pas trouvé',
	  'missing': 'Champs manquants:',
	  'invalidpasswd': 'Code ou mot de passe invalide',
	  'alreadyexists': 'Existe déjà',
	  'code': 'Code',
	  'passwd': 'Mot de passe',
	  'name': 'Nom',
	  'type': 'Type',
	  'content': 'Contenu',
	},
	'de-DE': {
	  'st201': 'Erstellt',
	  'st400': 'Schlechte Anfrage',
	  'st401': 'Sie müssen sich anmelden',
	  'st403': 'Sie haben keine Berechtigung',
	  'st404': 'Nicht gefunden',
	  'missing': 'Fehlende Felder:',
	  'invalidpasswd': 'Ungültiger Code oder Passwort',
	  'alreadyexists': 'Existiert bereits',
	  'code': 'Code',
	  'passwd': 'Kennwort',
	  'name': 'Name',
	  'type': 'Typ',
	  'content': 'Inhalt',
	},
	'it-IT': {
	  'st201': 'Creato',
	  'st400': 'Richiesta errata',
	  'st401': 'Devi effettuare il login',
	  'st403': 'Non hai i permessi',
	  'st404': 'Non trovato',
	  'missing': 'Campi mancanti:',
	  'invalidpasswd': 'Codice o password non validi',
	  'alreadyexists': 'Esiste già',
	  'code': 'Codice',
	  'passwd': 'Password',
	  'name': 'Nome',
	  'type': 'Tipo',
	  'content': 'Contenuto',
	},
	'pt-PT': {
	  'st201': 'Criado',
	  'st400': 'Mau pedido',
	  'st401': 'É necessário fazer login',
	  'st403': 'Não tem permissões',
	  'st404': 'Não encontrado',
	  'missing': 'Campos em falta:',
	  'invalidpasswd': 'Código inválido ou palavra-passe',
	  'alreadyexists': 'Já existe',
	  'code': 'Código',
	  'passwd': 'Senha',
	  'name': 'Nome',
	  'type': 'Tipo',
	  'content': 'Conteúdo',
	},
	'zh-CN': {
	  'st201': '创建',
	  'st400': '坏请求',
	  'st401': '您必须登录',
	  'st403': '你没有权限',
	  'st404': '未找到',
	  'missing': '缺少的字段。',
	  'invalidpasswd': '无效代码或密码',
	  'alreadyexists': '已经存在',
	  'code': '密码',
	  'passwd': '密码',
	  'name': '帐号',
	  'type': '类型',
	  'content': '内容',
	}
};

module.exports = (code, lang) => {
  const ldef = {en: 'en-US', es: 'es-ES', fr: 'fr-FR', de: 'de-DE', it: 'it-IT', pt: 'pt-PT', zh: 'zh-CN'};
  const lini = (lang) ? lang.substring(0, 2) : '';
  const lng = (lang && langs[lang]) ? lang : ((ldef[lini]) ? ldef[lini] : 'en-US');

  return langs[lng][code];
};
